spring.application.name=SpringbootDemo

server.port=8000

spring.datasource.url=jdbc:mysql://localhost:3306/ecomm
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


sonar.projectKey=6c5e7da906b5f5df9408109967a272c0e815bc76
sonar.organization=Arul-Guru
sonar.sources=src/main/java
sonar.tests=src/test/java

sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
#spring.profiles.active=prod


